mockserver:
  url: http://mockserver:1080
our:
  awesome:
    bank:
      name: T-Банк
spring:
  application:
    name: modulism
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:testdb;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
  jackson:
    serialization:
      WRITE_BIGDECIMAL_AS_PLAIN: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  sleuth:
    traceId128: true
    supportsJoin: false
management:
  observations:
    all:
      enabled: true
  tracing:
    enabled: true
    propagation.type: B3_MULTI
    sampling:
      probability: 1.0 # 1.0 means 100% of requests will be traced.
logging:
  level:
    ru.tbank: DEBUG
taxes:
  account: 101101
  bank: БАНК РОССИИ